# Permalinks
permalink:           pretty

# Setup
title:               Ryan Richbourg
tagline:             Ryan's Github Data Science Blog
url:                 http://rrichbourg.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ryan Richbourg
  url:               https://github.com/rrichbourg
  email:             ryanrichbourg3@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/rrichbourg

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
